name: bus-khoja-stack

services:
  # -------------------- Database --------------------
  postgres:
    image: postgres:15
    container_name: bus-khoja-postgres
    secrets:
      - db-password
    environment:
      POSTGRES_DB: bus-khoja
      POSTGRES_USER: Ruhan
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Ruhan -d bus-khoja"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # -------------------- Python Backend --------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bus-khoja-backend
    command: uv run main.py
    environment:
      DATABASE_URL: postgresql://Ruhan:hmmmmmmmmm@postgres:5432/bus-khoja
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  # -------------------- Next.js Frontend --------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bus-khoja-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

# -------------------- Secrets & Volumes --------------------
secrets:
  db-password:
    file: /db/password.txt

volumes:
  db-data:
