version: "3.9"

name: bus-khoja-stack

services:
  # -------------------- Database --------------------
  postgres:
    image: postgres:15
    container_name: bus-khoja-postgres
    secrets:
      - db-password
    environment:
      POSTGRES_DB: bus-khoja
      POSTGRES_USER: Ruhan
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Ruhan -d bus-khoja"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # -------------------- Python Backend --------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bus-khoja-backend
    command: uv run main.py
    environment:
      DATABASE_URL: postgresql://Ruhan:hmmmmmmmmm@postgres:5432/bus-khoja
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`buskhoja.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped

  # -------------------- Next.js Frontend --------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bus-khoja-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://buskhoja.xyz/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`buskhoja.xyz`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    depends_on:
      - backend
    restart: unless-stopped

  # -------------------- Traefik Reverse Proxy --------------------
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ruhan@buskhoja.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# -------------------- Secrets & Volumes --------------------
secrets:
  db-password:
    file: ./db/password.txt

volumes:
  db-data:
